export const Data = [
    {
        filters: [
            {
                src: "./assets/images/beach.jpg",
                alt: "An icon for the beach homes section",
                name: "Beach" 
            },
            {
                src: "./assets/images/boat.jpg",
                alt: "An icon for the boat homes section",
                name: "Boat" 
            },
            {
                src: "./assets/images/breakfast.jpg",
                alt: "An icon for the breakfast homes section",
                name: "Breakfast" 
            },
            {
                src: "./assets/images/camping.jpg",
                alt: "An icon for the camping homes section",
                name: "Camping" 
            },
            {
                src: "./assets/images/castle.jpg",
                alt: "An icon for the castle homes section",
                name: "Castle" 
            },
            {
                src: "./assets/images/cave.png",
                alt: "An icon for the cave homes section",
                name: "Camp" 
            },
            {
                src: "./assets/images/city.jpg",
                alt: "An icon for the city homes section",
                name: "City" 
            },
            {
                src: "./assets/images/history.webp",
                alt: "An icon for the historical homes section",
                name: "Historical Homes" 
            },
            {
                src: "./assets/images/mansion.jpg",
                alt: "An icon for the mansion homes section",
                name: "Mansions" 
            },
            {
                src: "./assets/images/pool.jpg",
                alt: "An icon for the pool homes section",
                name: "Pool" 
            },
            {
                src: "./assets/images/shared.jpg",
                alt: "An icon for the shared homes section",
                name: "Shared Homes" 
            },
            {
                src: "./assets/images/surfing.jpg",
                alt: "An icon for the surfing homes section",
                name: "Surfing" 
            },
            {
                src: "./assets/images/tree.png",
                alt: "An icon for the treehouses section",
                name: "Treehouses" 
            },
            {
                src: "./assets/images/tropical.jpg",
                alt: "An icon for the tropical homes section",
                name: "Tropical" 
            },
            {
                src: "./assets/images/vineyard.jpg",
                alt: "An icon for the vineyard homes section",
                name: "Vineyard" 
            },
        ],
        houses: [
            {
                src: "./assets/images/beach-ghana.webp",
                alt: "A beach house in Ghana",
                name: "Accra, Ghana",
                host: "Samoah Gyan",
                cost: "$345",
                date: "Available form Nov6-11",
                ratings: "4.5",
            },
            {
                src: "./assets/images/beach-spain.webp",
                alt: "A beach house in Spain",
                name: "Madrid, Spain",
                host: "Sergio Ramos",
                cost: "#1025",
                date: "Available from Oct27-30",
                ratings: "5.0",
            },
            {
                src: "./assets/images/boat-spain.webp",
                alt: "A boat house in Spain",
                name: "Bilbao, Spain",
                host: "Inaki Williams",
                cost: "$123",
                date: "Available from Nov12-19",
                ratings: "4.2",
            },
            {
                src: "./assets/images/boat-italy.webp",
                alt: "A boat house in Italy",
                name: "Napoli, Italy",
                host: "Stephen Elsharawwy",
                cost: "$69",
                date: "Available from Nov6-11",
                ratings: "$4.0",
            },
            {
                src: "./assets/images/breakfast-morocco.webp",
                alt: "A breakfast home in Morocco",
                name: "Rabat, Morocco",
                host: "Adaml Tarabt",
                cost: "$450",
                date: "Available from Oct31-Nov6",
                ratings: "3.7",
            },
            {
                src: "./assets/images/breakfast-turkey.webp",
                alt: "A breakfast home in turkey",
                name: "Istanbul, Turkey",
                host: "Hakan Calhanoglu",
                cost: "$65",
                date: "Available from Nov6-11",
                ratings: "4.8",
            },
            {
                src: "./assets/images/camping-Israel.webp",
                alt: "A camping home in Israel",
                name: "Jerusalem, Israel",
                host: "Yossi Benayoun",
                cost: "$60",
                date: "Available from Nov24-27",
                ratings: "4.0",
            },
            {
                src: "./assets/images/camping-jordan.webp",
                alt: "A camping home in Jordan",
                name: "Amman, Jordan",
                host: "Abdallah Nasseb",
                cost: "$75",
                date: "Available from Oct24-30",
                ratings: "4.5",
            },
            {
                src: "./assets/images/castle-italy.webp",
                alt: "A castle home in Italy",
                name: "Milan, Italy",
                host: "Giorgio Cheillini",
                cost: "$345",
                date: "Available from $450",
                ratings: "4.2",
            },
            {
                src: "./assets/images/castle-spain.webp",
                alt: "A castle home in Spain",
                name: "Barcelona, Spain",
                host: "Gerard Pique",
                cost: "#600",
                date: "Available from Jan12-14,2023",
                ratings: "5.0",
            },
            {
                src: "./assets/images/cave-greece.webp",
                alt: "A cave home in Greece",
                name: "Athens, Greece",
                host: "Kostas Tsimikas",
                cost: "$250",
                date: "Available from Oct24-31",
                ratings: "4.5",
            },
            {
                src: "./assets/images/cave-turkey.webp",
                alt: "A cave home in Turkey",
                name: "Istanbul,Turkey",
                host: "Cergiz Under",
                cost: "$150",
                date: "Available from Nov6-11",
                ratings: "4.8",
            },
            {
                src: "./assets/images/city-southafrica.webp",
                alt: "A city home in South Africa",
                name: "Pretoria, South Africa",
                host: "Tsiphiwe Tshabalala",
                cost: "$100",
                date: "Available from Nov6-11",
                ratings: "4.0",
            },
            {
                src: "./assets/images/city-uk.webp",
                alt: "A city home in th United Kingdom",
                name: "Edinburgh, Uk",
                host: "Mason Mount",
                cost: "$450",
                date: "Available from Jan12-14",
                ratings: "5.0",
            },
            {
                src: "./assets/images/historical-france.webp",
                alt: "A historical home in France",
                name: "Lyon, France",
                host: "Karim Benzema",
                cost: "$500",
                date: "Available from Dec23-31",
                ratings: "5.0",
            },
            {
                src: "./assets/images/historical-italy.webp",
                alt: "A historical home in Italy",
                name: "Turin, Italy",
                host: "Andrea Pirlo",
                cost: "$1025",
                date: "Available from Nov 6-10",
                ratings: "5.0",
            },
            {
                src: "./assets/images/mansion-france.webp",
                alt: "A mansion home in France",
                name: "Lille, France",
                host: "Olivier Giroud",
                cost: "$450",
                date: "Available from Dec23-31",
                ratings: "4.8",
            },
            {
                src: "./assets/images/mansion-portugal.webp",
                alt: "A mansion home in Porugal",
                name: "Lisbon, Portugal",
                host: "Rafael Leao",
                cost: "$350",
                date: "Available from Nov24-27",
                ratings: "4.0",
            },
            {
                src: "./assets/images/pool-abidjan.webp",
                alt: "A pool home in Ivory Coast",
                name: "Abidjan, Cote d'Ivoire",
                host: "Didier Drogba",
                cost: "$250",
                date: "Available from Dec1-6",
                ratings: "4.9",
            },
            {
                src: "./assets/images/pool-nigeria.webp",
                alt: "A pool home in Nigeria",
                name: "Lekki, Lagos",
                host: "John Mikel Obi",
                cost: "$100",
                date: "Available from Dec1-6",
                ratings: "4.8",
            },
            {
                src: "./assets/images/shared-abuja.webp",
                alt: "A shared home in Nigeria",
                name: "Maitama, Abuja",
                host: "Ademola Lookman",
                cost: "$150",
                date: "Available from Nov6-10",
                ratings: "4.9",
            },
            {
                src: "./assets/images/shared-lagos.webp",
                alt: "A shared home in Nigeria",
                name: "Lekki, Lagos",
                host: "Emmanuel Dennis",
                cost: "$200",
                date: "Available from Dec23-30",
                ratings: "4.5",
            },
            {
                src: "./assets/images/surf-france.webp",
                alt: "A surf home in France",
                name: "Marsielle, France",
                host: "Dimitri Payet",
                cost: "$250",
                date: "Available from Nov9-13",
                ratings: "4.2",
            },
            {
                src: "./assets/images/surf-portugal.webp",
                alt: "A surf home in Portugal",
                name: "Braga, Portugal",
                host: "Joao Cancelo",
                cost: "$200",
                date: "Available from Dec9-16",
                ratings: "4.5",
            },
            {
                src: "./assets/images/treehouse-france.webp",
                alt: "A Treehouse in France",
                name: "Bordeaux, France",
                host: "Benjamin Pavard",
                cost: "$300",
                date: "Available from Nov24-30",
                ratings: "4.0",
            },
            {
                src: "./assets/images/treehouse-greece.webp",
                alt: "A treehouse in Greece",
                name: "Santorini, Greece",
                host: "Kostas Manolas",
                cost: "$200",
                date: "Available from Nov6-10",
                ratings: "3.8",
            },
            {
                src: "./assets/images/tropical-barbados.webp",
                alt: "A tropical home in Barbados",
                name: "Barbados",
                host: "Rihannna",
                cost: "$900",
                date: "Available from Dec16-31",
                ratings: "5.0",
            },
            {
                src: "./assets/images/tropical-mexico.webp",
                alt: "A tropical home in Mexico",
                name: "Mexico City, Mexico",
                host: "Rafael Marquez",
                cost: "$100",
                date: "Available all through December",
                ratings: "4.0",
            },
            {
                src: "./assets/images/vineyard-cadiz.webp",
                alt: "A tropical home in Spain",
                name: "Cadiz, Spain",
                host: "Unai Simon",
                cost: "$180",
                date: "Available from Nov9-12",
                ratings: "3.8",
            },
            {
                src: "./assets/images/vineyard-spain.webp",
                alt: "A vineyard home in Mallorca",
                name: "Mallorca, Spain",
                host: "Dani Carvjal",
                cost: "$120",
                date: "Available from Nov 18-24",
                ratings: "4.0",
            }
        ]
    }
]